# Generated by Django 4.0.2 on 2022-09-18 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBook',
            fields=[
                ('Date', models.DateField(auto_now_add=True)),
                ('Accession_Number', models.AutoField(primary_key=True, serialize=False)),
                ('Author', models.CharField(max_length=400)),
                ('Title', models.CharField(max_length=500)),
                ('Volume', models.IntegerField(blank=True, null=True)),
                ('Place', models.CharField(max_length=500)),
                ('Publisher', models.CharField(max_length=400)),
                ('Year_Of_Publication', models.IntegerField(blank=True, null=True)),
                ('Source', models.CharField(blank=True, max_length=400, null=True)),
                ('Pages', models.IntegerField(blank=True, null=True)),
                ('Book_Number', models.IntegerField()),
                ('Bill_Number', models.IntegerField(blank=True, null=True)),
                ('Bill_Date', models.DateField(blank=True, null=True)),
                ('Withdrawn_Date', models.DateField(blank=True, null=True)),
                ('Remark', models.CharField(blank=True, max_length=1000, null=True)),
                ('class_No', models.IntegerField(blank=True, null=True)),
                ('Category', models.CharField(default=' ', max_length=100)),
                ('Available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddStudent',
            fields=[
                ('objectid', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Fathers_Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=500)),
                ('Roll_Number', models.BigIntegerField()),
                ('Year', models.IntegerField(default=0)),
                ('Branch', models.CharField(max_length=50)),
                ('Phone_Number', models.BigIntegerField()),
                ('Joining_Date', models.DateField()),
                ('Expiring_Date', models.DateField()),
                ('Library_ID', models.CharField(default=0, max_length=20)),
                ('Student_image', models.ImageField(default='', upload_to='img/')),
                ('Student_barcode', models.ImageField(default='', upload_to='img/')),
                ('Email', models.CharField(default='Not Present', max_length=200)),
                ('customuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('Faculty_image', models.ImageField(default='', upload_to='img/')),
                ('Branch', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=200, unique=True)),
                ('Username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=20)),
                ('Confirm', models.BooleanField(default=False)),
                ('customuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book_Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Return', models.DateTimeField(auto_now_add=True)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.addstudent')),
                ('bookno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.addbook')),
            ],
        ),
        migrations.CreateModel(
            name='Book_issued',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Issue', models.DateTimeField(auto_now_add=True)),
                ('Date_Return', models.DateTimeField(blank=True, null=True)),
                ('Return_Status', models.BooleanField(default=False)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.addstudent')),
                ('bookno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.addbook')),
            ],
        ),
    ]
